controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    differential_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # linear_actuator_controller:
    #   type: forward_command_controller/ForwardCommandController

differential_drive_controller:
  ros__parameters:

    publish_rate: 150.0

    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.21
    wheel_radius: 0.05

    use_stamped_vel: false

# linear_actuator_controller:
#   ros__parameters:
#     joints:
#       - actuator_rod_joint

#     interface_name: position